
[tool.pylint.messages_control]

disable = ["missing-function-docstring",
    "missing-module-docstring",
    "missing-final-newline",
    "missing-class-docstring",
    "no-value-for-parameter",
    "missing-timeout",
    "not-context-manager",
    "redefined-outer-name",
    R0801
    ]
    