name: CI/CD Workflow

on:
  push:
    branches:
      - '*' 

jobs:
  build_webservice:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set working directory
        run: echo "Setting working directory"
        working-directory: ./web_service
      - name: Build docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} -f ./web_service/Dockerfile .       
      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}
      - name: Run Docker container
        run: |
          docker run -p 9696:9696 ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

      - name: Wait for service to start
        run: sleep 10

      - name: Run tests
        run: python test.py
