name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build_webservice:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.LOCAL_IMAGE_NAME }} .
        
    - name: Run Docker container
      run: |
        docker run --env-file .env -d -it \
          --rm -v ${{ github.workspace }}:/app \
          -p 9696:9696 ${{ secrets.LOCAL_IMAGE_NAME }}

    - name: Wait for service to start
      run: sleep 10

    - name: Run tests
      run: python test.py
