name: CI tests

on:
  push:
    branches:
      - '*'
      
env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  REGISTRY_URL: ${{ vars.REGISTRY_URL }}
  PREFECT_API_SERVER: ${{ vars.PREFECT_API_SERVER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: echo image tag
        run: echo ${{ github.sha }}
      - name: Build docker image
        run:  docker build -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG --build-arg FLOW_NAME=${{ secrets.FLOW_NAME }} --build-arg PREFECT_API_SERVER=$PREFECT_API_SERVER --build-arg IMAGE_NAME=$IMAGE_NAME --build-arg REGISTRY_URL=$REGISTRY_URL --build-arg IMAGE_TAG=$IMAGE_TAG --build-arg PROJECT_NAME=${{ secrets.PROJECT_NAME }} --build-arg MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }} --build-arg MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }} --build-arg MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }} .
      - name: Push Docker image
        run: docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
         
  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: run tests
  #     run: |
  #       docker pull $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
  #       docker run --rm -i -e PYTHONPATH=src $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG kedro test

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    needs: build
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: deploy flow
      run: |
        docker pull $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
        docker run --rm -i -e PYTHONPATH=src $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG ./deploy.sh
