name: CI/CD Workflow

on:
  push:
    branches:
      - '*' 

jobs:
  build_webservice:
    runs-on: ubuntu-latest

    steps:
     - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
    - name: Build docker image
      run:  docker build -t $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG --build-arg REGISTRY_URL=$REGISTRY_URL --build-arg IMAGE_NAME=$IMAGE_NAME --build-arg IMAGE_TAG=$IMAGE_TAG .
    - name: Push Docker image
      run: docker push $REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
        
    - name: Run Docker container
      run: |
        docker run --env-file .env -d -it \
          --rm -v ${{ github.workspace }}:/app \
          -p 9696:9696 ${{ secrets.LOCAL_IMAGE_NAME }}

    - name: Wait for service to start
      run: sleep 10

    - name: Run tests
      run: python test.py
