name: CI/CD Workflow

on:
  push:
    branches:
      - '*' 

jobs:
  build_webservice:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set working directory
        working-directory: ./web_service
      - name: Build docker image
        run: |
          docker build -t bbilmez/heart_disease_xgb_model:v1 .
          #${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
           # --build-arg REGISTRY_URL=${{ env.REGISTRY_URL }} \
            #--build-arg IMAGE_NAME=${{ env.IMAGE_NAME }} \
            #--build-arg IMAGE_TAG=${{ env.IMAGE_TAG }} .
            
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run Docker container
        run: |
          docker run --env-file .env -d -it \
            --rm -v ${{ github.workspace }}:/app \
            -p 9696:9696 ${{ secrets.LOCAL_IMAGE_NAME }}

      - name: Wait for service to start
        run: sleep 10

      - name: Run tests
        run: python test.py
